name: MakeCode

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PXT
        run: npm install -g pxt

      - name: Select target
        run: pxt target calliopemini

      - name: Install dependencies
        run: pxt install

      - name: Build
        run: pxt build --cloud
        env:
          CI: true